[package]
name = "xtask"
version = "1.0.0"
authors = ["gediminas.luzys@gmail.com"]
license = "MIT"
edition = "2021"

[[bin]]
name = "xtask"
path = "xtask.rs"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
